// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(harmony_uniffiFFI)
import harmony_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_harmony_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_harmony_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureHarmonyUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol HarmonyEncodingFfiProtocol: AnyObject, Sendable {
    
    func decodeBytes(tokens: [UInt32], errors: String) throws  -> String
    
    func decodeUtf8(tokens: [UInt32]) throws  -> String
    
    func encode(text: String, allowedSpecial: [String]) throws  -> [UInt32]
    
    func isSpecialToken(token: UInt32)  -> Bool
    
    func name()  -> String
    
    func newStreamParser(role: String?, strict: Bool) throws  -> PicoHarmonyStreamParser
    
    func parseMessagesFromCompletionTokens(tokens: [UInt32], role: String?, strict: Bool) throws  -> String
    
    func render(messageJson: String, renderOptions: RenderOptionsFfi?) throws  -> [UInt32]
    
    func renderConversation(conversationJson: String, config: RenderConversationConfigFfi?) throws  -> [UInt32]
    
    func renderConversationForCompletion(conversationJson: String, nextTurnRole: String, config: RenderConversationConfigFfi?) throws  -> [UInt32]
    
    func renderConversationForTraining(conversationJson: String, config: RenderConversationConfigFfi?) throws  -> [UInt32]
    
    func specialTokens()  -> [String]
    
    func stopTokens() throws  -> [UInt32]
    
    func stopTokensForAssistantActions() throws  -> [UInt32]
    
}
open class HarmonyEncodingFfi: HarmonyEncodingFfiProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_harmony_uniffi_fn_clone_harmonyencodingffi(self.handle, $0) }
    }
public convenience init(name: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_constructor_harmonyencodingffi_new(
        FfiConverterString.lower(name),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_harmony_uniffi_fn_free_harmonyencodingffi(handle, $0) }
    }

    

    
open func decodeBytes(tokens: [UInt32], errors: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_decode_bytes(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt32.lower(tokens),
        FfiConverterString.lower(errors),$0
    )
})
}
    
open func decodeUtf8(tokens: [UInt32])throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_decode_utf8(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt32.lower(tokens),$0
    )
})
}
    
open func encode(text: String, allowedSpecial: [String])throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_encode(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),
        FfiConverterSequenceString.lower(allowedSpecial),$0
    )
})
}
    
open func isSpecialToken(token: UInt32) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_is_special_token(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(token),$0
    )
})
}
    
open func name() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_name(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func newStreamParser(role: String?, strict: Bool)throws  -> PicoHarmonyStreamParser  {
    return try  FfiConverterTypePicoHarmonyStreamParser_lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_new_stream_parser(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(role),
        FfiConverterBool.lower(strict),$0
    )
})
}
    
open func parseMessagesFromCompletionTokens(tokens: [UInt32], role: String?, strict: Bool)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_parse_messages_from_completion_tokens(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt32.lower(tokens),
        FfiConverterOptionString.lower(role),
        FfiConverterBool.lower(strict),$0
    )
})
}
    
open func render(messageJson: String, renderOptions: RenderOptionsFfi?)throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_render(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(messageJson),
        FfiConverterOptionTypeRenderOptionsFfi.lower(renderOptions),$0
    )
})
}
    
open func renderConversation(conversationJson: String, config: RenderConversationConfigFfi?)throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_render_conversation(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(conversationJson),
        FfiConverterOptionTypeRenderConversationConfigFfi.lower(config),$0
    )
})
}
    
open func renderConversationForCompletion(conversationJson: String, nextTurnRole: String, config: RenderConversationConfigFfi?)throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_render_conversation_for_completion(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(conversationJson),
        FfiConverterString.lower(nextTurnRole),
        FfiConverterOptionTypeRenderConversationConfigFfi.lower(config),$0
    )
})
}
    
open func renderConversationForTraining(conversationJson: String, config: RenderConversationConfigFfi?)throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_render_conversation_for_training(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(conversationJson),
        FfiConverterOptionTypeRenderConversationConfigFfi.lower(config),$0
    )
})
}
    
open func specialTokens() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_special_tokens(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func stopTokens()throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_stop_tokens(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func stopTokensForAssistantActions()throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_harmonyencodingffi_stop_tokens_for_assistant_actions(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHarmonyEncodingFfi: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HarmonyEncodingFfi

    public static func lift(_ handle: UInt64) throws -> HarmonyEncodingFfi {
        return HarmonyEncodingFfi(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HarmonyEncodingFfi) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HarmonyEncodingFfi {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HarmonyEncodingFfi, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHarmonyEncodingFfi_lift(_ handle: UInt64) throws -> HarmonyEncodingFfi {
    return try FfiConverterTypeHarmonyEncodingFfi.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHarmonyEncodingFfi_lower(_ value: HarmonyEncodingFfi) -> UInt64 {
    return FfiConverterTypeHarmonyEncodingFfi.lower(value)
}






public protocol PicoHarmonyGptOssProtocol: AnyObject, Sendable {
    
    /**
     * Streaming parse: returns an object you can feed tokens into.
     */
    func newStreamParser() throws  -> PicoHarmonyStreamParser
    
    /**
     * Batch parse: pass all completion token IDs.
     */
    func parseCompletionTokens(tokenIds: [UInt32]) throws  -> ParsedAssistant
    
}
open class PicoHarmonyGptOss: PicoHarmonyGptOssProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_harmony_uniffi_fn_clone_picoharmonygptoss(self.handle, $0) }
    }
public convenience init()throws  {
    let handle =
        try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_constructor_picoharmonygptoss_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_harmony_uniffi_fn_free_picoharmonygptoss(handle, $0) }
    }

    

    
    /**
     * Streaming parse: returns an object you can feed tokens into.
     */
open func newStreamParser()throws  -> PicoHarmonyStreamParser  {
    return try  FfiConverterTypePicoHarmonyStreamParser_lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonygptoss_new_stream_parser(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Batch parse: pass all completion token IDs.
     */
open func parseCompletionTokens(tokenIds: [UInt32])throws  -> ParsedAssistant  {
    return try  FfiConverterTypeParsedAssistant_lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonygptoss_parse_completion_tokens(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt32.lower(tokenIds),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePicoHarmonyGptOss: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PicoHarmonyGptOss

    public static func lift(_ handle: UInt64) throws -> PicoHarmonyGptOss {
        return PicoHarmonyGptOss(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PicoHarmonyGptOss) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PicoHarmonyGptOss {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PicoHarmonyGptOss, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePicoHarmonyGptOss_lift(_ handle: UInt64) throws -> PicoHarmonyGptOss {
    return try FfiConverterTypePicoHarmonyGptOss.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePicoHarmonyGptOss_lower(_ value: PicoHarmonyGptOss) -> UInt64 {
    return FfiConverterTypePicoHarmonyGptOss.lower(value)
}






public protocol PicoHarmonyStreamParserProtocol: AnyObject, Sendable {
    
    func currentChannel() throws  -> String?
    
    func currentContent() throws  -> String
    
    func currentContentType() throws  -> String?
    
    func currentRecipient() throws  -> String?
    
    func currentRole() throws  -> String?
    
    /**
     * Finish parsing. Can be called once; subsequent calls error.
     */
    func finish() throws  -> ParsedAssistant
    
    func lastContentDelta() throws  -> String?
    
    func messagesJson() throws  -> String
    
    /**
     * Feed one token id; returns the delta (if any) plus channel metadata.
     */
    func process(tokenId: UInt32) throws  -> StreamDelta
    
    func processEos() throws 
    
    func stateJson() throws  -> String
    
    func tokens() throws  -> [UInt32]
    
}
open class PicoHarmonyStreamParser: PicoHarmonyStreamParserProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_harmony_uniffi_fn_clone_picoharmonystreamparser(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_harmony_uniffi_fn_free_picoharmonystreamparser(handle, $0) }
    }

    

    
open func currentChannel()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_current_channel(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func currentContent()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_current_content(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func currentContentType()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_current_content_type(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func currentRecipient()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_current_recipient(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func currentRole()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_current_role(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Finish parsing. Can be called once; subsequent calls error.
     */
open func finish()throws  -> ParsedAssistant  {
    return try  FfiConverterTypeParsedAssistant_lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_finish(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func lastContentDelta()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_last_content_delta(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func messagesJson()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_messages_json(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Feed one token id; returns the delta (if any) plus channel metadata.
     */
open func process(tokenId: UInt32)throws  -> StreamDelta  {
    return try  FfiConverterTypeStreamDelta_lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_process(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(tokenId),$0
    )
})
}
    
open func processEos()throws   {try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_process_eos(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func stateJson()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_state_json(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func tokens()throws  -> [UInt32]  {
    return try  FfiConverterSequenceUInt32.lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_method_picoharmonystreamparser_tokens(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePicoHarmonyStreamParser: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PicoHarmonyStreamParser

    public static func lift(_ handle: UInt64) throws -> PicoHarmonyStreamParser {
        return PicoHarmonyStreamParser(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PicoHarmonyStreamParser) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PicoHarmonyStreamParser {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PicoHarmonyStreamParser, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePicoHarmonyStreamParser_lift(_ handle: UInt64) throws -> PicoHarmonyStreamParser {
    return try FfiConverterTypePicoHarmonyStreamParser.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePicoHarmonyStreamParser_lower(_ value: PicoHarmonyStreamParser) -> UInt64 {
    return FfiConverterTypePicoHarmonyStreamParser.lower(value)
}




public struct ParsedAssistant: Equatable, Hashable {
    public var reasoning: String?
    public var finalText: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reasoning: String?, finalText: String?) {
        self.reasoning = reasoning
        self.finalText = finalText
    }

    
}

#if compiler(>=6)
extension ParsedAssistant: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParsedAssistant: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParsedAssistant {
        return
            try ParsedAssistant(
                reasoning: FfiConverterOptionString.read(from: &buf), 
                finalText: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ParsedAssistant, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.reasoning, into: &buf)
        FfiConverterOptionString.write(value.finalText, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedAssistant_lift(_ buf: RustBuffer) throws -> ParsedAssistant {
    return try FfiConverterTypeParsedAssistant.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedAssistant_lower(_ value: ParsedAssistant) -> RustBuffer {
    return FfiConverterTypeParsedAssistant.lower(value)
}


public struct ParsedMessagesJson: Equatable, Hashable {
    public var messagesJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(messagesJson: String) {
        self.messagesJson = messagesJson
    }

    
}

#if compiler(>=6)
extension ParsedMessagesJson: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParsedMessagesJson: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParsedMessagesJson {
        return
            try ParsedMessagesJson(
                messagesJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ParsedMessagesJson, into buf: inout [UInt8]) {
        FfiConverterString.write(value.messagesJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedMessagesJson_lift(_ buf: RustBuffer) throws -> ParsedMessagesJson {
    return try FfiConverterTypeParsedMessagesJson.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParsedMessagesJson_lower(_ value: ParsedMessagesJson) -> RustBuffer {
    return FfiConverterTypeParsedMessagesJson.lower(value)
}


public struct RenderConversationConfigFfi: Equatable, Hashable {
    public var autoDropAnalysis: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(autoDropAnalysis: Bool) {
        self.autoDropAnalysis = autoDropAnalysis
    }

    
}

#if compiler(>=6)
extension RenderConversationConfigFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRenderConversationConfigFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RenderConversationConfigFfi {
        return
            try RenderConversationConfigFfi(
                autoDropAnalysis: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: RenderConversationConfigFfi, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.autoDropAnalysis, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderConversationConfigFfi_lift(_ buf: RustBuffer) throws -> RenderConversationConfigFfi {
    return try FfiConverterTypeRenderConversationConfigFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderConversationConfigFfi_lower(_ value: RenderConversationConfigFfi) -> RustBuffer {
    return FfiConverterTypeRenderConversationConfigFfi.lower(value)
}


public struct RenderOptionsFfi: Equatable, Hashable {
    public var conversationHasFunctionTools: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(conversationHasFunctionTools: Bool) {
        self.conversationHasFunctionTools = conversationHasFunctionTools
    }

    
}

#if compiler(>=6)
extension RenderOptionsFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRenderOptionsFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RenderOptionsFfi {
        return
            try RenderOptionsFfi(
                conversationHasFunctionTools: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: RenderOptionsFfi, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.conversationHasFunctionTools, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderOptionsFfi_lift(_ buf: RustBuffer) throws -> RenderOptionsFfi {
    return try FfiConverterTypeRenderOptionsFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderOptionsFfi_lower(_ value: RenderOptionsFfi) -> RustBuffer {
    return FfiConverterTypeRenderOptionsFfi.lower(value)
}


public struct StreamDelta: Equatable, Hashable {
    public var channel: String?
    public var delta: String?
    public var contentType: String?
    public var recipient: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(channel: String?, delta: String?, contentType: String?, recipient: String?) {
        self.channel = channel
        self.delta = delta
        self.contentType = contentType
        self.recipient = recipient
    }

    
}

#if compiler(>=6)
extension StreamDelta: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamDelta: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamDelta {
        return
            try StreamDelta(
                channel: FfiConverterOptionString.read(from: &buf), 
                delta: FfiConverterOptionString.read(from: &buf), 
                contentType: FfiConverterOptionString.read(from: &buf), 
                recipient: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: StreamDelta, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.channel, into: &buf)
        FfiConverterOptionString.write(value.delta, into: &buf)
        FfiConverterOptionString.write(value.contentType, into: &buf)
        FfiConverterOptionString.write(value.recipient, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamDelta_lift(_ buf: RustBuffer) throws -> StreamDelta {
    return try FfiConverterTypeStreamDelta.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamDelta_lower(_ value: StreamDelta) -> RustBuffer {
    return FfiConverterTypeStreamDelta.lower(value)
}


public enum PicoHarmonyError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Msg(String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension PicoHarmonyError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePicoHarmonyError: FfiConverterRustBuffer {
    typealias SwiftType = PicoHarmonyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PicoHarmonyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Msg(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PicoHarmonyError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Msg(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePicoHarmonyError_lift(_ buf: RustBuffer) throws -> PicoHarmonyError {
    return try FfiConverterTypePicoHarmonyError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePicoHarmonyError_lower(_ value: PicoHarmonyError) -> RustBuffer {
    return FfiConverterTypePicoHarmonyError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRenderConversationConfigFfi: FfiConverterRustBuffer {
    typealias SwiftType = RenderConversationConfigFfi?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRenderConversationConfigFfi.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRenderConversationConfigFfi.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRenderOptionsFfi: FfiConverterRustBuffer {
    typealias SwiftType = RenderOptionsFfi?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRenderOptionsFfi.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRenderOptionsFfi.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
public func loadHarmonyEncodingFfi(name: String)throws  -> HarmonyEncodingFfi  {
    return try  FfiConverterTypeHarmonyEncodingFfi_lift(try rustCallWithError(FfiConverterTypePicoHarmonyError_lift) {
    uniffi_harmony_uniffi_fn_func_load_harmony_encoding_ffi(
        FfiConverterString.lower(name),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_harmony_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_harmony_uniffi_checksum_func_load_harmony_encoding_ffi() != 53996) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_decode_bytes() != 27414) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_decode_utf8() != 30460) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_encode() != 65487) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_is_special_token() != 40868) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_name() != 45247) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_new_stream_parser() != 59666) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_parse_messages_from_completion_tokens() != 7590) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_render() != 54572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_render_conversation() != 11423) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_render_conversation_for_completion() != 3223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_render_conversation_for_training() != 43988) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_special_tokens() != 58858) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_stop_tokens() != 24280) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_harmonyencodingffi_stop_tokens_for_assistant_actions() != 8707) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonygptoss_new_stream_parser() != 27673) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonygptoss_parse_completion_tokens() != 62688) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_current_channel() != 1857) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_current_content() != 32808) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_current_content_type() != 37792) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_current_recipient() != 61496) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_current_role() != 12802) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_finish() != 8845) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_last_content_delta() != 48984) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_messages_json() != 58680) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_process() != 50278) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_process_eos() != 10926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_state_json() != 57174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_method_picoharmonystreamparser_tokens() != 42903) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_constructor_harmonyencodingffi_new() != 36483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_harmony_uniffi_checksum_constructor_picoharmonygptoss_new() != 35399) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureHarmonyUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all